services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        user: '${WWWUSER:-sail}'
        uid: '${WWWUID:-1000}'
    container_name: laravel_app
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - MEMCACHED_HOST=memcached
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  # Redis for Queue
  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Memcached for Cache
  memcached:
    image: memcached:alpine
    container_name: laravel_memcached
    restart: unless-stopped
    ports:
      - "11211:11211"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
